name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: naestia/release@v0
        with:
          tag_prefix: "v"
          github_token: ${{ secrets.GITHUB_TOKEN }}